-- Run this in Supabase SQL Editor to store landing-page email signups.

create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  email text not null unique,
  created_at timestamptz not null default now()
);

alter table public.leads enable row level security;

drop policy if exists "Allow anon insert leads" on public.leads;
create policy "Allow anon insert leads"
on public.leads
for insert
to anon
with check (true);

drop policy if exists "Allow anon select leads" on public.leads;
create policy "Allow anon select leads"
on public.leads
for select
to anon
using (true);

